package proyectoCajero;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author franz
 */
public class ConsolaCajero extends javax.swing.JFrame {

    String textoBoton1;
    String textoBoton2;
    String textoBoton3;
    String textoBoton4;
    String textoPin;
    Registro r = new Registro();
    boolean pinCorrecto;

    public ConsolaCajero() {
        initComponents();
        Pin.setVisible(false);
        Boton1.setVisible(false);
        Boton6.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton4 = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Pin = new javax.swing.JPasswordField();
        TextoCajero = new javax.swing.JLabel();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Boton4.setText("Acceder Cajero");
        Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton4MouseClicked(evt);
            }
        });
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });

        Boton1.setText(" ");
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1MouseClicked(evt);
            }
        });
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Boton2.setText("Registrar Empleado");
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton2MouseClicked(evt);
            }
        });
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        Boton3.setText("Registrar Cliente");
        Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton3MouseClicked(evt);
            }
        });
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        Pin.setText("jPasswordField1");
        Pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PinMouseClicked(evt);
            }
        });
        Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinActionPerformed(evt);
            }
        });

        TextoCajero.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        TextoCajero.setText("¡Bienvenido al Banco Fidelitas! Seleccione una opcion:");

        Boton5.setText("Salir");
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton5MouseClicked(evt);
            }
        });
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Boton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextoCajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoCajero)
                        .addComponent(Pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(Boton1)
                .addGap(12, 12, 12)
                .addComponent(Boton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton4)
                    .addComponent(Boton5)
                    .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseClicked
        textoBoton4 = Boton4.getText();

        if (textoBoton4.equals("Acceder Cajero")) {
            JOptionPane.showMessageDialog(null, "Ingrese su tarjeta");
            TextoCajero.setText(" Ingrese su Pin: ");
            Pin.setVisible(true);
            Boton2.setVisible(false);
            Boton3.setVisible(false);
            Boton4.setText("Ingresar");
            Boton5.setVisible(true);
        }

        if (textoBoton4.equals("Ingresar")) {
            textoPin = Pin.getText();
            pinCorrecto = false;
            pinCorrecto = r.verificarPin(Integer.parseInt(textoPin));

            if (pinCorrecto) {
                Pin.setVisible(false);
                TextoCajero.setText(" Seleccione una opcion: ");
                Boton1.setVisible(true);
                Boton1.setText("Extraer Dinero");
                Boton2.setVisible(true);
                Boton2.setText("Depositar Dinero");
                Boton3.setVisible(true);
                Boton3.setText("Consultar Saldo");
                Boton4.setText("Cambio de Pin");
            }
            if (!pinCorrecto) {
                Pin.setText("INCORRECTO");
                TextoCajero.setText(" Pin Incorrecto. Intente de nuevo: ");

            }
        }
        if (textoBoton4.equals("Cambio de Pin")) {
            TextoCajero.setText(" Ingrese su Pin: ");
            Pin.setVisible(true);
            Boton1.setVisible(false);
            Boton2.setVisible(false);
            Boton3.setVisible(false);
            Boton4.setText("Ingresar PIN actual");
        }

        if (textoBoton4.equals("Ingresar PIN actual")) {
            textoPin = Pin.getText();
            pinCorrecto = false;
            pinCorrecto = r.verificarPin(Integer.parseInt(textoPin));
            if (pinCorrecto) {
                TextoCajero.setText(" Ingrese su nuevo Pin: ");
                Boton4.setText("Ingresar nuevo PIN");
            }
            if (!pinCorrecto) {
                Pin.setText("INCORRECTO");
                TextoCajero.setText(" Pin Incorrecto. Intente de nuevo: ");
            }
        }

        if (textoBoton4.equals("Ingresar nuevo PIN")) {
            String textoNuevoPin = Pin.getText();
            r.cambiarPin((Integer.parseInt(textoPin)), (Integer.parseInt(textoNuevoPin)));
            JOptionPane.showMessageDialog(null, "Pin fue modificado exitosamente");
            cargarMenuPrincipal();

        }
        
        if (textoBoton4.equals("$50")) {
            boolean seExtrajo = extraerDinero(50,(Integer.parseInt(textoPin)));
            if(seExtrajo){
                JOptionPane.showMessageDialog(null, "Tome su dinero");
                cargarMenuPrincipal();
            }
            if(!seExtrajo){
                JOptionPane.showMessageDialog(null, "Fondos insuficientes!"); 
                cargarMenuPrincipal();
            }
        }
        
        if (textoBoton4.equals("Depositar")) {
            int cantidad = Integer.parseInt(Boton6.getText());
            JOptionPane.showMessageDialog(null, "Ingrese el dinero al cajero"); 
            r.depositarDinero(cantidad, (Integer.parseInt(textoPin)));
            cargarMenuPrincipal();
        }

    }//GEN-LAST:event_Boton4MouseClicked

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton4ActionPerformed

    private void PinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PinMouseClicked
        Pin.setText("");
    }//GEN-LAST:event_PinMouseClicked

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton3ActionPerformed

    private void PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinActionPerformed

    private void Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseClicked
        textoBoton3 = Boton3.getText();
        if (textoBoton3.equals("Registrar Cliente")) {
            setVisible(false);
            r.agregarCliente();
            setVisible(true);
        }
        
        if (textoBoton3.equals("$20")) {
            boolean seExtrajo = extraerDinero(20,(Integer.parseInt(textoPin)));
            if(seExtrajo){
                JOptionPane.showMessageDialog(null, "Tome su dinero");
                cargarMenuPrincipal();
            }
            if(!seExtrajo){
                JOptionPane.showMessageDialog(null, "Fondos insuficientes!"); 
                cargarMenuPrincipal();
            }
        }
    }//GEN-LAST:event_Boton3MouseClicked

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        textoBoton2 = Boton2.getText();
        if (textoBoton2.equals("Registrar Empleado")) {
            setVisible(false);
            r.agregarEmpleado();
            setVisible(true);
        }
        
        if (textoBoton2.equals("$10")) {
            boolean seExtrajo = extraerDinero(10,(Integer.parseInt(textoPin)));
            if(seExtrajo){
                JOptionPane.showMessageDialog(null, "Tome su dinero");
                cargarMenuPrincipal();
            }
            if(!seExtrajo){
                JOptionPane.showMessageDialog(null, "Fondos insuficientes!");  
                cargarMenuPrincipal();
            }
        }
        
        if (textoBoton2.equals("Depositar Dinero")) {
            TextoCajero.setText("Cuánto Dinero desea depositar?");
            Boton1.setVisible(false);
            Boton2.setVisible(false);
            Boton3.setVisible(false);
            Boton4.setText("Depositar");
            Boton4.setVisible(true);
            Boton6.setVisible(true);
        }
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseClicked
        cargarMenuPrincipal();
        JOptionPane.showMessageDialog(null, "Retire su tarjeta");
    }//GEN-LAST:event_Boton5MouseClicked

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
        textoBoton1 = Boton1.getText();
        if (textoBoton1.equals("Extraer Dinero")) {
            TextoCajero.setText("Cuánto Dinero desea extraer?");
            Boton1.setText("$5");
            Boton2.setText("$10");
            Boton3.setText("$20");
            Boton4.setText("$50");
            setVisible(true);
        }
        
        if (textoBoton1.equals("$5")) {
            boolean seExtrajo = extraerDinero(5,(Integer.parseInt(textoPin)));
            if(seExtrajo){
                JOptionPane.showMessageDialog(null, "Tome su dinero");
                cargarMenuPrincipal();
            }
            if(!seExtrajo){
                JOptionPane.showMessageDialog(null, "Fondos insuficientes!");  
                cargarMenuPrincipal();
            }
        }
    }//GEN-LAST:event_Boton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsolaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsolaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsolaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsolaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsolaCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JTextField Boton6;
    private javax.swing.JPasswordField Pin;
    private javax.swing.JLabel TextoCajero;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void cargarMenuPrincipal() {
        TextoCajero.setText("¡Bienvenido al Banco Fidelitas! Seleccione una opcion:");
        Boton2.setVisible(true);
        Boton2.setText("Registrar Empleado");
        Boton3.setVisible(true);
        Boton3.setText("Registrar Cliente");
        Boton4.setText("Acceder Cajero");
        Pin.setVisible(false);
        Boton1.setVisible(false);
        Boton5.setVisible(false);
        Boton6.setVisible(false);
    }
    
    private boolean extraerDinero(int cantidad, int pin){
        boolean fondosSuficientes;
        fondosSuficientes = r.extraerDinero(cantidad, pin);
        return fondosSuficientes;
    }
}
